version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: docker/tensorflow-training/Dockerfile
    image: tensorflow-train
    ports:
      - 8080:8080
    volumes:
    - ./src:/app/src:Z
    - ./data:/app/data:Z
    - ./config:/app/config:Z
    - ./log/:/app/log:Z
    command: "bash"
    tty: true
    stdin_open: true