version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: docker/tensorflow-serve/Dockerfile
    image: tensorflow-serve
    ports:
      - 8080:8080
      - 8501:8501
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ./config/key.json
    volumes:
    - ./src:/app/src:Z
    - ./data:/app/data:Z
    - ./config:/app/config:Z
    - ./log/:/app/log:Z
    command: "bash"
    tty: true
    stdin_open: true